export const prismjsLanguages = {
  abap: "ABAP",
  abnf: "ABNF",
  actionscript: "ActionScript",
  ada: "Ada",
  adoc: "AsciiDoc",
  agda: "Agda",
  al: "AL",
  antlr4: "ANTLR4",
  apl: "APL",
  apacheconf: "Apache Configuration",
  apex: "Apex",
  applescript: "AppleScript",
  aql: "AQL",
  arduino: "Arduino",
  arff: "ARFF",
  armasm: "ARM Assembly",
  "arm-asm": "ARM Assembly",
  art: "Arturo",
  arturo: "Arturo",
  asciidoc: "AsciiDoc",
  asm6502: "6502 Assembly",
  asmatmel: "Atmel AVR Assembly",
  aspnet: "ASP.NET (C#)",
  atom: "Markup",
  autohotkey: "AutoHotkey",
  autoit: "AutoIt",
  avisynth: "AviSynth",
  avs: "AviSynth",
  "avro-idl": "Avro IDL",
  avdl: "Avro IDL",
  awk: "AWK",
  bash: "Bash",
  basic: "BASIC",
  batch: "Batch",
  bbcode: "BBcode",
  bbj: "BBj",
  bicep: "Bicep",
  birb: "Birb",
  bison: "Bison",
  bnf: "BNF",
  bqn: "BQN",
  brainfuck: "Brainfuck",
  brightscript: "BrightScript",
  bro: "Bro",
  bsl: "BSL (1C:Enterprise)",
  c: "C",
  cfscript: "CFScript",
  cfc: "CFScript",
  chaiscript: "ChaiScript",
  cil: "CIL",
  cilkc: "Cilk/C",
  "cilk-c": "Cilk/C",
  cilkcpp: "Cilk/C++",
  "cilk-cpp": "Cilk/C++",
  cilk: "Cilk/C++",
  clike: "C-like",
  clojure: "Clojure",
  cmake: "CMake",
  cobol: "COBOL",
  coffee: "CoffeeScript",
  coffeescript: "CoffeeScript",
  conc: "Concurnas",
  concurnas: "Concurnas",
  context: "LaTeX",
  cooklang: "Cooklang",
  coq: "Coq",
  cpp: "C++",
  crystal: "Crystal",
  cs: "C#",
  csharp: "C#",
  cshtml: "Razor C#",
  css: "CSS",
  "css-extras": "CSS Extras",
  csp: "Content-Security-Policy",
  csv: "CSV",
  cue: "CUE",
  cypher: "Cypher",
  d: "D",
  dart: "Dart",
  dataweave: "DataWeave",
  dax: "DAX",
  dhall: "Dhall",
  diff: "Diff",
  django: "Django/Jinja2",
  "dns-zone-file": "DNS zone file",
  "dns-zone": "DNS zone file",
  docker: "Docker",
  dockerfile: "Docker",
  dot: "DOT (Graphviz)",
  dotnet: "C#",
  ebnf: "EBNF",
  editorconfig: "EditorConfig",
  eiffel: "Eiffel",
  ejs: "EJS",
  elisp: "Lisp",
  elixir: "Elixir",
  elm: "Elm",
  emacs: "Lisp",
  "emacs-lisp": "Lisp",
  erb: "ERB",
  erlang: "Erlang",
  eta: "EJS",
  etlua: "Embedded Lua templating",
  "excel-formula": "Excel Formula",
  factor: "Factor",
  false: "False",
  "firestore-security-rules": "Firestore security rules",
  flow: "Flow",
  fortran: "Fortran",
  fsharp: "F#",
  ftl: "FreeMarker Template Language",
  g4: "ANTLR4",
  gamemakerlanguage: "GameMaker Language",
  gap: "GAP (CAS)",
  gawk: "AWK",
  gcode: "G-code",
  gdscript: "GDScript",
  gedcom: "GEDCOM",
  gettext: "gettext",
  gherkin: "Gherkin",
  git: "Git",
  gitignore: ".ignore",
  glsl: "GLSL",
  gml: "GameMaker Language",
  gn: "GN",
  gni: "GN",
  go: "Go",
  "go-module": "Go module",
  "go-mod": "Go module",
  gradle: "Gradle",
  graphql: "GraphQL",
  groovy: "Groovy",
  gv: "DOT (Graphviz)",
  haml: "Haml",
  handlebars: "Handlebars",
  haskell: "Haskell",
  haxe: "Haxe",
  hbs: "Handlebars",
  hcl: "HCL",
  hgignore: ".ignore",
  hlsl: "HLSL",
  hoon: "Hoon",
  hpkp: "HTTP Public-Key-Pins",
  hs: "Haskell",
  hsts: "HTTP Strict-Transport-Security",
  html: "Markup",
  http: "HTTP",
  ichigojam: "IchigoJam",
  icon: "Icon",
  "icu-message-format": "ICU Message Format",
  idr: "Idris",
  idris: "Idris",
  iecst: "Structured Text (IEC 61131-3)",
  ignore: ".ignore",
  inform7: "Inform 7",
  ini: "Ini",
  ino: "Arduino",
  io: "Io",
  j: "J",
  java: "Java",
  javadoc: "JavaDoc",
  javadoclike: "JavaDoc-like",
  javastacktrace: "Java stack trace",
  javascript: "JavaScript",
  jexl: "Jexl",
  jinja2: "Django/Jinja2",
  jolie: "Jolie",
  jq: "JQ",
  js: "JavaScript",
  jsdoc: "JSDoc",
  "js-extras": "JS Extras",
  json: "JSON",
  json5: "JSON5",
  jsonp: "JSONP",
  jsstacktrace: "JS stack trace",
  "js-templates": "JS Templates",
  jsx: "JSX",
  julia: "Julia",
  keepalived: "Keepalived Configure",
  keyman: "Keyman",
  kotlin: "Kotlin",
  kt: "Kotlin",
  kts: "Kotlin",
  kumir: "KuMir (КуМир)",
  kum: "KuMir (КуМир)",
  kusto: "Kusto",
  latex: "LaTeX",
  latte: "Latte",
  ld: "GNU Linker Script",
  less: "Less",
  lilypond: "LilyPond",
  "linker-script": "GNU Linker Script",
  liquid: "Liquid",
  lisp: "Lisp",
  livescript: "LiveScript",
  llvm: "LLVM IR",
  log: "Log file",
  lolcode: "LOLCODE",
  lua: "Lua",
  ly: "LilyPond",
  magma: "Magma (CAS)",
  makefile: "Makefile",
  markdown: "Markdown",
  markup: "Markup",
  "markup-templating": "Markup templating",
  mata: "Mata",
  mathematica: "Wolfram language",
  mathml: "Markup",
  matlab: "MATLAB",
  maxscript: "MAXScript",
  md: "Markdown",
  mel: "MEL",
  mermaid: "Mermaid",
  metafont: "METAFONT",
  mizar: "Mizar",
  mongodb: "MongoDB",
  monkey: "Monkey",
  moon: "MoonScript",
  moonscript: "MoonScript",
  mscript: "PowerQuery",
  mustache: "Handlebars",
  n1ql: "N1QL",
  n4js: "N4JS",
  n4jsd: "N4JS",
  "nand2tetris-hdl": "Nand To Tetris HDL",
  nani: "Naninovel Script",
  naniscript: "Naninovel Script",
  nasm: "NASM",
  nb: "Wolfram language",
  neon: "NEON",
  nevod: "Nevod",
  nginx: "nginx",
  nim: "Nim",
  nix: "Nix",
  npmignore: ".ignore",
  nsis: "NSIS",
  objc: "Objective-C",
  objectivec: "Objective-C",
  objectpascal: "Pascal",
  ocaml: "OCaml",
  odin: "Odin",
  opencl: "OpenCL",
  openqasm: "OpenQasm",
  oscript: "BSL (1C:Enterprise)",
  oz: "Oz",
  parigp: "PARI/GP",
  parser: "Parser",
  pascal: "Pascal",
  pascaligo: "Pascaligo",
  pbfasm: "PureBasic",
  pcaxis: "PC-Axis",
  pcode: "PeopleCode",
  peoplecode: "PeopleCode",
  perl: "Perl",
  php: "PHP",
  phpdoc: "PHPDoc",
  "php-extras": "PHP Extras",
  "plant-uml": "PlantUML",
  plantuml: "PlantUML",
  plsql: "PL/SQL",
  po: "gettext",
  powerquery: "PowerQuery",
  powershell: "PowerShell",
  processing: "Processing",
  prolog: "Prolog",
  promql: "PromQL",
  properties: ".properties",
  protobuf: "Protocol Buffers",
  pq: "PowerQuery",
  psl: "PATROL Scripting Language",
  pug: "Pug",
  puppet: "Puppet",
  pure: "Pure",
  purebasic: "PureBasic",
  purescript: "PureScript",
  purs: "PureScript",
  py: "Python",
  python: "Python",
  px: "PC-Axis",
  q: "Q (kdb+ database)",
  qasm: "OpenQasm",
  qml: "QML",
  qore: "Qore",
  qs: "Q#",
  qsharp: "Q#",
  r: "R",
  racket: "Racket",
  razor: "Razor C#",
  rb: "Ruby",
  rbnf: "BNF",
  reason: "Reason",
  regex: "Regex",
  rego: "Rego",
  renpy: "Ren'py",
  res: "ReScript",
  rescript: "ReScript",
  rest: "reST (reStructuredText)",
  rip: "Rip",
  rkt: "Racket",
  roboconf: "Roboconf",
  robot: "Robot Framework",
  robotframework: "Robot Framework",
  rpy: "Ren'py",
  rq: "SPARQL",
  rss: "Markup",
  ruby: "Ruby",
  rust: "Rust",
  sas: "SAS",
  sass: "Sass (Sass)",
  scala: "Scala",
  scheme: "Scheme",
  sclang: "SuperCollider",
  scss: "Sass (SCSS)",
  sh: "Bash",
  shell: "Bash",
  "shell-session": "Shell session",
  "sh-session": "Shell session",
  shellsession: "Shell session",
  shortcode: "BBcode",
  smali: "Smali",
  smalltalk: "Smalltalk",
  smarty: "Smarty",
  sml: "SML",
  smlnj: "SML",
  sln: "Solution file",
  sol: "Solidity (Ethereum)",
  solidity: "Solidity (Ethereum)",
  "solution-file": "Solution file",
  soy: "Soy (Closure Template)",
  sparql: "SPARQL",
  "splunk-spl": "Splunk SPL",
  sqf: "SQF: Status Quo Function (Arma 3)",
  sql: "SQL",
  squirrel: "Squirrel",
  ssml: "Markup",
  stan: "Stan",
  stata: "Stata Ado",
  stylus: "Stylus",
  supercollider: "SuperCollider",
  svg: "Markup",
  swift: "Swift",
  systemd: "Systemd configuration file",
  t4: "T4 Text Templates (C#)",
  "t4-cs": "T4 Text Templates (C#)",
  "t4-templating": "T4 templating",
  "t4-vb": "T4 Text Templates (VB)",
  tap: "TAP",
  tcl: "Tcl",
  tex: "LaTeX",
  textile: "Textile",
  toml: "TOML",
  tremor: "Tremor",
  trickle: "Tremor",
  trig: "Turtle",
  troy: "Tremor",
  ts: "TypeScript",
  tsconfig: "TypoScript",
  tsx: "TSX",
  tt2: "Template Toolkit 2",
  turtle: "Turtle",
  twig: "Twig",
  typescript: "TypeScript",
  typoscript: "TypoScript",
  uc: "UnrealScript",
  unrealscript: "UnrealScript",
  uorazor: "UO Razor Script",
  uri: "URI",
  url: "URI",
  uscript: "UnrealScript",
  v: "V",
  vala: "Vala",
  vb: "Visual Basic",
  vba: "Visual Basic",
  vbnet: "VB.Net",
  velocity: "Velocity",
  verilog: "Verilog",
  vhdl: "VHDL",
  vim: "vim",
  "visual-basic": "Visual Basic",
  warpscript: "WarpScript",
  wasm: "WebAssembly",
  webidl: "Web IDL",
  "web-idl": "Web IDL",
  webmanifest: "JSON",
  wgsl: "WGSL",
  wiki: "Wiki markup",
  wl: "Wolfram language",
  wolfram: "Wolfram language",
  wren: "Wren",
  xeora: "Xeora",
  xeoracube: "Xeora",
  xls: "Excel Formula",
  xlsx: "Excel Formula",
  xml: "Markup",
  "xml-doc": "XML doc (.net)",
  xojo: "Xojo (REALbasic)",
  xquery: "XQuery",
  yaml: "YAML",
  yang: "YANG",
  yml: "YAML",
  zig: "Zig",
} as const

type PrismjsLanguage = keyof typeof prismjsLanguages

type PrismjsLanguageValue = (typeof prismjsLanguages)[PrismjsLanguage]

/**
 * @description The language from the prismjsLanguages object
 */
export type Language = PrismjsLanguageValue | PrismjsLanguage | string

/**
 * @description Get the language from the prismjsLanguages object
 * @param language - The language to get
 * @returns The language from the prismjsLanguages object
 */
export const getPrismjsLanguage = (language: Language) => {
  if (Object.keys(prismjsLanguages).includes(language)) {
    return prismjsLanguages[language]
  }

  if (Object.values(prismjsLanguages).includes(language as PrismjsLanguageValue)) {
    return language
  }

  return language
}
