# deploy.yml
name: Deploy develop branch to servers
on:
  push:
    branches:
      - develop
      
env:
    SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }} # 服务器私钥
    REMOTE_HOST: ${{ secrets.HOST }} # 服务器IP地址
    REMOTE_USER: ${{ secrets.USER }} # 服务器用户名
    REMOTE_PORT: ${{ secrets.PORT }} # 服务器ssh端口
    TARGET: 'var/www/test' # 项目路径
    cache-name: note

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
        
      # 使用 nodejs 18
      - uses: actions/setup-node@v1
        with:
            node-version: 18

      #缓存依赖
      - name: Cache nodemodules
        uses: actions/cache@v1
        env:
            cache-name: cache-node-modules
        with:
            # 需要缓存的文件的路径
            path: ./node_modules 
            # 对缓存的文件指定的唯一标识
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package.json') }} 
            # 用于没有再找目标key的缓存的backup选项
            restore-keys: |
                ${{ runner.os }}-build-${{ env.cache-name }}-
                ${{ runner.os }}-build-
                ${{ runner.os }}-
                
      # install
      - name: Install
        run: yarn

      # 打包
      - name: Build
        run: yarn build

      # Deploy
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ env.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ env.REMOTE_HOST }}
          REMOTE_USER: ${{ env.REMOTE_USER }}
          REMOTE_PORT: ${{ env.REMOTE_PORT }}
          TARGET: ${{ env.TARGET }}
          SOURCE: 'public/'
