# deploy.yml
name: Deploy master branch to servers
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master

      # 使用 nodejs 18
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 启用 Corepack
      - name: Enable Corepack
        run: corepack enable

      # 使用正确版本的 Yarn
      - name: Set Yarn Version
        run: corepack prepare yarn@4.5.1 --activate

      # 缓存依赖
      - name: Cache Yarn
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .yarn/patches
            .yarn/plugins
            .yarn/releases
            .yarn/sdksimmutable
            .yarn/versions
          key: ${{ runner.os }}-yarn-blog-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-blog-
            ${{ runner.os }}-yarn-

      # install
      - name: Install
        run: yarn

      # 打包
      - name: Build
        run: yarn build

      # Deploy
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }} # 私钥
          REMOTE_HOST: ${{ secrets.HOST }} # 服务器地址
          REMOTE_USER: ${{ secrets.USER }} # 服务器用户名
          REMOTE_PORT: ${{ secrets.PORT }} # 服务器ssh端口
          TARGET: ${{ secrets.TARGET }}
          SOURCE: 'public/'